### ISSUE TITLE
Custom Scheduler Docs

### ISSUE THREAD

**Issue by danielschonfeld** [twitter/heron#833] opened 2016-05-29 16:30 UTC
The docs for creating your own custom scheduler seem to be out of date.  Most links don't work and also I don't believe some of the interfaces mentioned are still required? I don't seem to see an `IConfig` at all same goes for `IRuntimeManager`.

Also it appears as if `IUploader` is not required per new scheduler, but only if you want to implement a different style uploader.

**Comment by kramasamy** [comment] 2016-05-29 17:45
@danielschonfeld - thanks for pointing out. We are in the process of updating it.

**Comment by danielschonfeld** [comment] 2016-05-29 18:00
No problem! Thank you for all the work you guys have and are doing.

Just so I'm clear is IScheduler and ILauncher the absolute minimum required
at the moment for a custom scheduler?

**Comment by kramasamy** [comment] 2016-05-30 05:47
@danielschonfeld - yes. Please look at the local, aurora and slurm scheduler implementation.

**Comment by maosongfu** [comment] 2016-05-30 06:24
Yeah the doc is a little outdated. And we are working to improve it. Same issue reported here: #809

**Comment by kramasamy** [comment] 2016-05-30 23:26
duplicate of #809

**Closed by kramasamy** 2016-05-30 23:26 UTC
