### ISSUE TITLE
Failed to invoke IScheduler as library

### ISSUE THREAD

**Issue by jiandongjia** [twitter/heron#874] opened 2016-06-07 04:50 UTC
hi guys:

I was successful in the local mode.
now  I  want run  with  aurora cluster.
meson  and aurora  have been installed successfully.

upder the auraro directory,  scheduler.yaml  and   statemgr.yaml   contents are as follows

------------------------scheduler.yaml 
```
heron.class.scheduler:                       com.twitter.heron.scheduler.aurora.AuroraScheduler
heron.class.launcher:                        com.twitter.heron.scheduler.aurora.AuroraLauncher
heron.package.core.uri:     file:///home/q/heron/heron-0.14.0/heron/dist/heron-core.tar.gz
heron.directory.sandbox.java.home:  /home/q/java8/jdk1.8.0_91/
heron.scheduler.is.service:                  False
```
------------------------statemgr.yaml 
```
heron.class.state.manager: com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager
heron.statemgr.connection.string:  "xxxx:2181,xxx:2181,xxx:2181"
heron.statemgr.root.path: "/heron"
heron.statemgr.zookeeper.is.initialize.tree: True
heron.statemgr.zookeeper.session.timeout.ms: 30000
heron.statemgr.zookeeper.connection.timeout.ms: 30000
heron.statemgr.zookeeper.retry.count: 10
heron.statemgr.zookeeper.retry.interval.ms: 10000

```
run command follows,   error   "Failed to invoke IScheduler as library "  
$ sudo heron submit aurora/root/test   /home/q/heron/heron-0.14.0/heron/examples/heron-examples.jar   
com.twitter.heron.examples.ExclamationTopology    ExclamationTopology

**Comment by nlu90** [comment] 2016-06-08 18:59
@jiandongjia Is this a duplicate of #885 ?

**Comment by jiandongjia** [comment] 2016-06-09 02:33
yes,thanks, I added the --verbose parameter and found that it was a question of permission.

**Closed** 2016-06-09 02:34 UTC
