### ISSUE TITLE
Re-enable fail on javadoc error

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#766] opened 2016-05-25 03:35 UTC
We had to disable fail-on-javadoc-error since it failed on travis although passing locally. Figure out why and re-enable it.

**Comment by kramasamy** [comment] 2016-05-27 07:02
@billonahill - this is completed I believe. Can we close this?

**Comment by billonahill** [comment] 2016-05-27 15:55
No, it's still disabled:
https://github.com/twitter/heron/blob/master/website/scripts/javadocs.sh#L2

**Comment by objmagic** [comment] 2016-06-21 00:40
I added ``set -e`` in commit https://github.com/twitter/heron/commit/7fb03ebc352cacfaac0ccaaae6006fccf0f3b449 and the CI worked fine. However, I failed to realize the error happens nondeterministically. The actual problem may be related to parallel building of protobuf Java files.

This means some PRs could be blocked by this problem. An immediate fix could be to remove ``set -e`` again.

**Comment by kramasamy** [comment] 2016-06-21 05:23
can you explain when the java docs are built? If you could introduce a bazel dependency it will be nice.

**Comment by taishi8117** [comment] 2016-06-21 21:10
Not using `tools/travis-ci/bazel.rc` for `javadoc.sh` might be the root cause of this issue -- that case, #968 should resolve this.

**Comment by objmagic** [comment] 2016-09-04 18:22
I believe this issue was fixed via #968. Feel free to close this.

**Closed** 2017-01-15 06:03 UTC
