### ISSUE TITLE
Shorten the travis-ci building time

### ISSUE THREAD

**Issue by maosongfu** [twitter/heron#799] opened 2016-05-25 23:54 UTC
A job taking longer than 50 minutes on travis-ci.org will be terminated like this:
The job exceeded the maximum time limit for jobs, and has been terminated.

Currently, heron travis-ci job runs: building, unit testing, style checking and integration tests, serially. And it is very likely the job exceeds 50mins.

**Comment by billonahill** [comment] 2016-05-26 16:00
@maosongfu ran a build without stylechecks (was that just java, or python, c too?) and the build time dropped by 20-30 minutes so we should pursue optimizations here.

- One question we have is why do the java checkstyles seem to happen serially? Maybe this has something to do with the action events/listener model. Can we parallelize this?
- Another possible solution: create a checkstyle mode that checks the entire codebase once, before the build proceeds without checkstyle checks. Theory is that a one-time check would be faster than many smaller ones. Challenge with that is getting the equivalent of `find . -name "*.java"` relative to heron root from bazel.

**Comment by billonahill** [comment] 2016-05-26 16:19
For item 2 above, theory confirmed. If would implement something like this, maybe as a sh_binary that relies on the checkstyle java_library, we'd be set.

```
$ time java -cp checkstyle-6.18-all.jar com.puppycrawl.tools.checkstyle.Main \
  -c tools/java/src/com/twitter/bazel/checkstyle/coding_style.xml \
  `find {heron,tools,integration-test}/. -name "*.java"`
Starting audit...
Audit done.

real	0m5.016s
user	0m13.773s
sys	0m0.517s
```

**Comment by billonahill** [comment] 2016-05-26 16:59
As expected this is proving difficult to do in bazel. The sh_binary target needs to be able to get the checkstyle jars and configs as well as all java files in the repo. I can get the jars, but 2 and 3 are proving tricky. Trying some hacks like this:

`BUILD`:
```
sh_binary(
    name = "checkstyle_all_java",
    srcs = ["checkstyle.sh"],
    data = ['//3rdparty/java:checkstyle'],
)
```

`checkstyle.sh`:
```
#!/bin/bash

JARS=`find . -name "*\.jar" | tr '\n' ":"`

# TODO: This is janky and doesn't actually work. Can't get all java files from this location
JAVA_FILES=`find ../{heron,tools,integration-test}/. -name "*.java"`

echo pwd: `pwd`
echo classpath: $JARS
echo JAVA_FILES: $JAVA_FILES

# TODO: coding_style.xml doesn't actually resolve here
time java -cp $JARS com.puppycrawl.tools.checkstyle.Main \
  -c tools/java/src/com/twitter/bazel/checkstyle/coding_style.xml \
  $JAVA_FILES
```
Then run with:
```
$ bazel run :checkstyle_all_java
```

**Comment by nlu90** [comment] 2016-05-26 17:07
`git rev-parse --show-toplevel` can locate the heron root dir.

```
[tw-mbp-nlu contributors (master)]$ git rev-parse --show-toplevel
/Users/nlu/workspace/heron
```

**Comment by billonahill** [comment] 2016-05-26 17:22
Thanks @nlu90 that's such a good hack and I think that will work for me.

To expand on item 2 above, the idea is that for the CI build only, we do two things:
1. Remove the current checkstyles that happen via the javac listener here:
https://github.com/twitter/heron/blob/master/tools/travis-ci/bazel.rc#L19
2. Add a one-time call to a target like the one I'm describing above to check the entire repo in one shot, before we proceed to the rest of the build, that no longer includes checkstyle verification.

**Comment by maosongfu** [comment] 2016-05-26 23:31
Also, I can try to reduce the results-pulling-interval in integration tests, while increasing the amount of pulling attempts. But this may reduce no more than 5 mins; not significant.

**Comment by billonahill** [comment] 2016-05-31 21:21
@maosongfu in #818 the java checkstyle is done once for the entire repo at the start, which takes 7 seconds, but the build still take 42 minutes. How did you assert that 20-30 minutes would be saved without checkstyles?

**Comment by billonahill** [comment] 2016-06-02 22:41
Investigation in #818 shows the the checkstyles are not the cause of the delay. #854 shows more detailed timings. The build is in fact spent in the main build:
```
===> Task duration summary for scripts/travis/build.sh
===========================================================
heron build 0:23:07
heron test non-flaky    0:03:41
heron test flaky    0:01:26
heron build tarpkgs 0:00:25
heron build binpkgs 0:00:22

===> Task duration summary for scripts/travis/test.sh
===========================================================
heron build integration-test    0:00:32
heron client install    0:00:19
heron integration-test local    0:05:17
heron integration-test  0:06:50

===> Task duration summary for scripts/travis/ci.sh
===========================================================
make site   0:02:00
scripts/travis/build.sh 0:29:01
scripts/travis/test.sh      0:12:58
```
```

**Comment by maosongfu** [comment] 2016-06-02 23:16
Hmm interesting, according to the log:
make site   0:02:00
scripts/travis/build.sh 0:29:01
scripts/travis/test.sh      0:12:58
--------
the whole Travis-Ci building can be completed in 44mins, much shorter than expected.

**Comment by billonahill** [comment] 2016-06-03 06:58
These timings don't include a few more minutes of setup for the host. The build has been taking about 47 or so minutes for a while. Are you saying you'd expect longer?

**Comment by maosongfu** [comment] 2016-06-03 07:37
Yeah originally the timeout is 50mins and every building in the afternoon (maybe that's a busy time and travis-ci is shared host?) will exceed the timeout and fail.

**Comment by billonahill** [comment] 2016-06-03 16:30
I tried doubling the parallelism in #857 but that didn't help. We must be using all available cores already.

**Comment by billonahill** [comment] 2016-06-13 22:27
Closing this for now since travis ci max time has been extended and the bulk of the time spent seems to be the compile. We can reopen if there are suggestions for how to speed up compile.

**Closed by billonahill** 2016-06-13 22:27 UTC
Labels: enhancement

**Comment by huijunw** [comment] 2017-02-23 00:32
@billonahill 'travis ci max time has been extended' how do you extend it? in what config? I was trying to extend it in my forked repo

**Comment by billonahill** [comment] 2017-02-27 17:39
@huijunw what is the answer?

**Comment by huijunw** [comment] 2017-02-27 17:49
karthik said twitter/heron paid travis ci so that ci does not kill it when compiling time is longer than 50min. but in my forked repo, my account does not pay ci, as a result, i cannot compile heron in my forked repo.
