### ISSUE TITLE
bookeeper is crashing when using gcp

### ISSUE THREAD

**Issue by mjschmidt** [twitter/heron#2586] opened 2017-11-24 17:58 UTC
@sijie any idea why this may be?

Was following this documentation https://twitter.github.io/heron/docs/operators/deployment/schedulers/kubernetes/#google-container-engine

Would I be able to use the stateful bookkeeper for this?

**Comment by mjschmidt** [comment] 2017-11-24 18:37
It looks like stateful bookkeeper did work when I brought up a new gcp cluster

**Comment by sijie** [comment] 2017-11-24 19:05
@mjschmidt what kind of errors do you encounter?

**Comment by sijie** [comment] 2017-11-24 19:06
do you mean daemonset doesn't work for you and statefulset works for you?

**Comment by mjschmidt** [comment] 2017-11-24 20:20
Yes. The daemonset would get up and running, but upon trying to launch a topology the bookeepers go into a crash loop.

**Comment by sijie** [comment] 2017-11-24 20:27
@mjschmidt do you any logs about the crash loop? and how many nodes do you use? I am wondering if this is related to the number of nodes you are using. because daemonset start one pod each node.

**Comment by mjschmidt** [comment] 2017-11-24 22:25
Just 3 nodes total. was just trying to get a quick and dirty heron cluster
up for a conference. Unfortunately no logs.

**Comment by sijie** [comment] 2017-11-24 23:57
Okay. I will try to reproduce myself and see if I can find the problem.

**Comment by kramasamy** [comment] 2018-02-24 05:02
@mjschmidt  - closing this issue. Reopen if there is a problem.

**Closed by kramasamy** 2018-02-24 05:02 UTC
